name: Update Badges

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Update README badges
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Badges will be automatically updated via shields.io')
            // The badges in README.md use dynamic shields.io URLs that update automatically